# C++ Language Justfile
# Works for any year

# Get the root directory and language template directory
root_dir := justfile_directory() / ".." / ".."
template_dir := justfile_directory() / "template"

# Create a new day
create year day:
  #!/usr/bin/env bash
  set -euo pipefail
  
  day_dir="{{root_dir}}/{{year}}/{{day}}/cpp"
  mkdir -p "$day_dir/inputs"
  
  # Copy template files
  cp {{template_dir}}/part1.cpp "$day_dir/"
  cp {{template_dir}}/part2.cpp "$day_dir/"
  cp {{template_dir}}/Makefile "$day_dir/"
  
  # Create empty input files
  touch "$day_dir/inputs/input.txt"
  touch "$day_dir/inputs/test.txt"
  
  echo "Created {{year}}/{{day}}/cpp with template files"

# Get inputs for a day
get-inputs year day:
  {{root_dir}}/scripts/get-inputs.sh --day {{day}} --year {{year}} --root-dir {{root_dir}}/{{year}}/{{day}}/cpp

# Run a solution
run year day part:
  @cd {{root_dir}}/{{year}}/{{day}}/cpp && make -s part{{part}} && ./part{{part}}

# Test a specific part
test year day part:
  @cd {{root_dir}}/{{year}}/{{day}}/cpp && make -s test{{part}}

# Test all parts
test-all year day:
  @cd {{root_dir}}/{{year}}/{{day}}/cpp && make -s test
