# Rust Language Justfile
# Works for any year

# Get the root directory and language template directory
root_dir := justfile_directory() / ".." / ".."
template_dir := justfile_directory() / "template"

# Create a new day
create year day:
  #!/usr/bin/env bash
  set -euo pipefail
  
  day_dir="{{root_dir}}/{{year}}/{{day}}"
  mkdir -p "$day_dir"
  cd "$day_dir"
  cargo generate --path {{template_dir}} --name rust

# Get inputs for a day
get-inputs year day:
  {{root_dir}}/scripts/get-inputs.sh --day {{day}} --year {{year}} --root-dir {{root_dir}}/{{year}}/{{day}}/rust

# Run a solution
run year day part:
  @cd {{root_dir}}/{{year}}/{{day}}/rust && cargo run --quiet --bin part{{part}}

# Test a specific part
test year day part:
  @cd {{root_dir}}/{{year}}/{{day}}/rust && cargo test --quiet part{{part}}

# Test all parts
test-all year day:
  @cd {{root_dir}}/{{year}}/{{day}}/rust && cargo test --quiet
